"""python-cloudcix settings"""

# COP(API)
CLOUDCIX_API_URL = ''
CLOUDCIX_API_USERNAME = ''
CLOUDCIX_API_PASSWORD = ''
CLOUDCIX_API_KEY = ''
CLOUDCIX_API_VERSION = 2
CLOUDCIX_API_V2_URL = ''

# Region(Robot)
ROBOT_USERNAME = ''
ROBOT_PASSWORD = ''
ROBOT_API_KEY = ''
