"""
Constants for the different states in the CloudCIX system
"""

IN_API = -1
IGNORE = 0
REQUESTED = 1
BUILDING = 2
UNRESOURCED = 3
RUNNING = 4
QUIESCE = 5
QUIESCED = 6
RESTART = 7
SCRUB = 8
SCRUB_QUEUE = 9
RUNNING_UPDATE = 10
RUNNING_UPDATING = 11
QUIESCING = 12
RESTARTING = 13
SCRUB_PREP = 14
QUIESCED_UPDATE = 15
QUIESCED_UPDATING = 16
SCRUBBING = 17
CLOSED = 99
