project:
  name: Wils-Big-Project

subnets:
  - name: Subnet-One
    gateway: 192.168.123.1
    mask: 24

vms:
  random: false
  count: 0
  vm_list:
    - name: VM-ONE
      dns: 91.103.0.1,8.8.8.8
      cpu: 1
      ram: 1
      image_id: 3
      gateway_subnet: 192.168.123.1/24
      ip_addresses:
        - address: 192.168.123.2
          nat: True
      storage_type_id: 1
      storages:
        - name: 'HDD-ONE'
          gb: 600
          primary: true

firewall_rules:
  - allow: true
    destination: '192.168.123.1/24'
    protocol: 'any'
    source: '*'
    debug_logging: True
    pci_logging: False
