project:
  name: Phantom-VM-Test

subnets:
  - name: Subnet-One
    gateway: 192.168.123.1
    mask: 24

vms:
  random: false
  count: 0
  vm_list:
    - name: VM-ONE
      dns: 91.103.0.1,8.8.8.8
      cpu: 4
      ram: 8
      image_id: 14
      gateway_subnet: 192.168.123.1/24
      ip_addresses:
        - address: 192.168.123.2
          nat: True
      storage_type_id: 1
      storages:
        - name: 'HDD-ONE'
          gb: 50
          primary: true
        - name: 'HDD-TWO'
          gb: 50
          primary: false
