project:
  name: Test-Project24

subnets:
  - name: Subnet-One
    gateway: 192.168.123.1
    mask: 24

vpns:
  - description: VPN-One
    vpn_type: site_to_site
    ike_authentication: md5
    ike_encryption: aes-256-cbc
    ike_lifetime: 18000
    ike_dh_groups: group2
    ike_gateway_value: 91.103.3.30
    ike_gateway_type: public_ip
    ike_pre_shared_key: test
    ike_version: v1-only
    ike_mode: main
    ipsec_authentication: hmac-md5-96
    ipsec_encryption: aes-256-cbc
    ipsec_lifetime: 18000
    ipsec_pfs_groups: group2
    ipsec_establish_time: immediately
    routes:
      - local_subnet: 192.168.123.1/24
        remote_subnet: 172.16.33.0/24
      - local_subnet: 192.168.123.1/24
        remote_subnet: 10.10.0.0/16

vms:
  random: false
  count: 1
  vm_list:
    - name: VM-ONE
      dns: 91.103.0.1,8.8.8.8
      cpu: 2
      ram: 4
      image_id: 17
      gateway_subnet: 192.168.123.1/24
      ip_addresses:
        - address: 192.168.123.2
          nat: True
      storage_type_id: 1
      storages:
        - name: 'HDD-ONE'
          gb: 20
          primary: true
firewall_rules:
  - allow: true
    destination: '192.168.123.1/24'
    protocol: 'any'
    source: '91.103.3.36'
    debug_logging: True
    pci_logging: False
